version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jasmine-ts
    versions:
    - 0.3.2
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.6
    - 3.6.7
    - 3.6.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: jasmine
    versions:
    - 3.6.4
